/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package edu.hotel.layered.view;

import edu.hotel.layered.controller.CustomerController;
import edu.hotel.layered.dto.CustomerDto;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author Yasas Randeeka
 */
public class CustomerView extends javax.swing.JFrame {
    private CustomerController customerController;
    /**
     * Creates new form CustomerView
     */
    public CustomerView() {
        this.customerController=new CustomerController();
        initComponents();
        loadCustomers();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCustomer = new javax.swing.JPanel();
        btnCustSearch = new javax.swing.JButton();
        btnCustUpdate = new javax.swing.JButton();
        lblMangeCustomer = new javax.swing.JLabel();
        lblCustId = new javax.swing.JLabel();
        txtCustId = new javax.swing.JTextField();
        lblFirstName = new javax.swing.JLabel();
        lblLastName = new javax.swing.JLabel();
        btnCustomerAdd = new javax.swing.JButton();
        txtLastName = new javax.swing.JTextField();
        txtFirstName = new javax.swing.JTextField();
        txtAddress = new javax.swing.JTextField();
        lblAddress = new javax.swing.JLabel();
        txtContactNo = new javax.swing.JTextField();
        lblContactNo = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        lblEmail = new javax.swing.JLabel();
        btnToHome = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCustomer = new javax.swing.JTable();
        btnCustDelete = new javax.swing.JButton();
        btnCusClear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btnCustSearch.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnCustSearch.setText("Search");
        btnCustSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCustSearchActionPerformed(evt);
            }
        });

        btnCustUpdate.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnCustUpdate.setText("Update");
        btnCustUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCustUpdateActionPerformed(evt);
            }
        });

        lblMangeCustomer.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        lblMangeCustomer.setText("Manage Customer");

        lblCustId.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblCustId.setText("Customer ID");

        txtCustId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCustIdActionPerformed(evt);
            }
        });

        lblFirstName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblFirstName.setText("First Name");

        lblLastName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblLastName.setText("Last Name");

        btnCustomerAdd.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnCustomerAdd.setText("Add");
        btnCustomerAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCustomerAddActionPerformed(evt);
            }
        });

        lblAddress.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblAddress.setText("Address");

        lblContactNo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblContactNo.setText("Contact No.");

        lblEmail.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblEmail.setText("Email");

        btnToHome.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnToHome.setText("Home");
        btnToHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnToHomeActionPerformed(evt);
            }
        });

        tblCustomer.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblCustomer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCustomerMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblCustomer);

        btnCustDelete.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnCustDelete.setText("Delete");
        btnCustDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCustDeleteActionPerformed(evt);
            }
        });

        btnCusClear.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnCusClear.setText("Clear");
        btnCusClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCusClearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jCustomerLayout = new javax.swing.GroupLayout(jCustomer);
        jCustomer.setLayout(jCustomerLayout);
        jCustomerLayout.setHorizontalGroup(
            jCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jCustomerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addGap(15, 15, 15))
            .addGroup(jCustomerLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jCustomerLayout.createSequentialGroup()
                        .addComponent(btnCustomerAdd)
                        .addGap(40, 40, 40)
                        .addComponent(btnCustSearch)
                        .addGap(45, 45, 45)
                        .addComponent(btnCustUpdate)
                        .addGap(40, 40, 40)
                        .addComponent(btnCustDelete)
                        .addGap(31, 31, 31)
                        .addComponent(btnCusClear))
                    .addComponent(lblFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(323, Short.MAX_VALUE))
            .addGroup(jCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jCustomerLayout.createSequentialGroup()
                    .addGap(245, 245, 245)
                    .addComponent(lblMangeCustomer)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 275, Short.MAX_VALUE)
                    .addComponent(btnToHome)
                    .addGap(34, 34, 34))
                .addGroup(jCustomerLayout.createSequentialGroup()
                    .addGap(16, 16, 16)
                    .addGroup(jCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblCustId, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblContactNo, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(134, 134, 134)
                    .addGroup(jCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtContactNo, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtCustId, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(356, 356, 356)))
        );
        jCustomerLayout.setVerticalGroup(
            jCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jCustomerLayout.createSequentialGroup()
                .addGap(111, 111, 111)
                .addComponent(lblFirstName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 169, Short.MAX_VALUE)
                .addGroup(jCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCustSearch)
                    .addComponent(btnCustUpdate)
                    .addComponent(btnCustDelete)
                    .addComponent(btnCusClear)
                    .addComponent(btnCustomerAdd))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jCustomerLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jCustomerLayout.createSequentialGroup()
                            .addGroup(jCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jCustomerLayout.createSequentialGroup()
                                    .addComponent(lblMangeCustomer)
                                    .addGap(26, 26, 26))
                                .addComponent(btnToHome, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addGroup(jCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtCustId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblCustId)))
                        .addGroup(jCustomerLayout.createSequentialGroup()
                            .addGap(104, 104, 104)
                            .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(18, 18, 18)
                    .addGroup(jCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblLastName)
                        .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(20, 20, 20)
                    .addGroup(jCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblAddress)
                        .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtContactNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblContactNo))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(jCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblEmail))
                    .addGap(374, 374, 374)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 26, Short.MAX_VALUE)
                .addComponent(jCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCustSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCustSearchActionPerformed
        // TODO add your handling code here:
        searchCustomer();
    }//GEN-LAST:event_btnCustSearchActionPerformed

    private void btnCustUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCustUpdateActionPerformed
        // TODO add your handling code here:
        updateCustomer();
    }//GEN-LAST:event_btnCustUpdateActionPerformed

    private void btnCustomerAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCustomerAddActionPerformed
        // TODO add your handling code here:
        saveCustomer();
    }//GEN-LAST:event_btnCustomerAddActionPerformed

    private void btnToHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnToHomeActionPerformed
        // TODO add your handling code here:
        new HomeView().close(this);
        new HomeView().setVisible(true);
    }//GEN-LAST:event_btnToHomeActionPerformed

    private void txtCustIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCustIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCustIdActionPerformed

    private void btnCustDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCustDeleteActionPerformed
        // TODO add your handling code here:
        deleteCustomer();
    }//GEN-LAST:event_btnCustDeleteActionPerformed

    private void btnCusClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCusClearActionPerformed
        // TODO add your handling code here:
        clear();
    }//GEN-LAST:event_btnCusClearActionPerformed

    private void tblCustomerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCustomerMouseClicked
        // TODO add your handling code here:
        displayCustomer();
    }//GEN-LAST:event_tblCustomerMouseClicked
    private void clear(){
        txtCustId.setText("");
        txtContactNo.setText("");
        txtAddress.setText("");
        txtEmail.setText("");
        txtFirstName.setText("");
        txtLastName.setText("");
    }
    private void loadCustomers(){
        try {
            String columns[] = {"Id", "Name", "Contact No", "Address", "Email"};
            DefaultTableModel dtm = new DefaultTableModel(columns, 0) {
                @Override
                public boolean isCellEditable(int row, int column) {
                    return false;
                }
            };
            
            tblCustomer.setModel(dtm);
            List<CustomerDto> customerDtos = customerController.getAllCustomer();

            for (CustomerDto customerDto : customerDtos) {
                Object[] rowData = {customerDto.getCustomerId(), customerDto.getFirstName()+" "+ customerDto.getLastName(),
                    customerDto.getContactNo(),customerDto.getAddress(), customerDto.getEmail()};
                dtm.addRow(rowData);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Loading Error-"+e);
        }
    }
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(CustomerView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(CustomerView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(CustomerView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(CustomerView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new CustomerView().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCusClear;
    private javax.swing.JButton btnCustDelete;
    private javax.swing.JButton btnCustSearch;
    private javax.swing.JButton btnCustUpdate;
    private javax.swing.JButton btnCustomerAdd;
    private javax.swing.JButton btnToHome;
    private javax.swing.JPanel jCustomer;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAddress;
    private javax.swing.JLabel lblContactNo;
    private javax.swing.JLabel lblCustId;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblFirstName;
    private javax.swing.JLabel lblLastName;
    private javax.swing.JLabel lblMangeCustomer;
    private javax.swing.JTable tblCustomer;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtContactNo;
    private javax.swing.JTextField txtCustId;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtLastName;
    // End of variables declaration//GEN-END:variables

    private void saveCustomer() {
        int choice=JOptionPane.showConfirmDialog(rootPane, "Are you sure?", "Save Customer",
                JOptionPane.YES_NO_CANCEL_OPTION,JOptionPane.INFORMATION_MESSAGE);
        try {
            if(choice==JOptionPane.YES_OPTION){
                CustomerDto customerDto=new CustomerDto(0,txtFirstName.getText(),
                    txtLastName.getText(),Integer.parseInt(txtContactNo.getText()),
                    txtAddress.getText(),txtEmail.getText());

                String result=customerController.saveCustomer(customerDto);
                if(result.equals("Succeed")){
                   JOptionPane.showMessageDialog(null, " Saved Customer Successfully");
                   clear();
                   loadCustomers();
                }
                else{
                    JOptionPane.showMessageDialog(null, "Save Customer Failed");
                }
            }
        } catch (Exception ex){
            Logger.getLogger(CustomerView.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Error Input Details");
        }
    }

    private void searchCustomer() {
        int id=0;
        try {
            if(!txtCustId.getText().equals("")){
                id=Integer.parseInt(txtCustId.getText());
            }
            else{
                JOptionPane.showMessageDialog(rootPane, "Please Enter Customer Id");
                return;
            }
            CustomerDto cusDto=customerController.getCustomer(id);
            txtFirstName.setText(cusDto.getFirstName());
            txtLastName.setText(cusDto.getLastName());
            txtAddress.setText(cusDto.getAddress());
            txtContactNo.setText(String.valueOf(cusDto.getContactNo()));
            txtEmail.setText(cusDto.getEmail());
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Not Found Details!!");
            clear();
        }
    }

    private void displayCustomer() {
        if(!txtCustId.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "First Clear Loaded Customer Details!");
            return;
        }
        int selectedRow=tblCustomer.getSelectedRow();
        //{"Id", "Name", "Contact No", "Address", "Email"};
        if(selectedRow!=-1){
            DefaultTableModel model=(DefaultTableModel)tblCustomer.getModel();
            
            txtCustId.setText(String.valueOf(model.getValueAt(selectedRow, 0)));
            String name=String.valueOf(model.getValueAt(selectedRow, 1));
            txtFirstName.setText(name.split(" ")[0]);
            txtLastName.setText(name.split(" ")[1]);
            
            txtAddress.setText(String.valueOf(model.getValueAt(selectedRow, 3)));
            txtEmail.setText(String.valueOf(model.getValueAt(selectedRow, 4)));
            txtContactNo.setText(String.valueOf(model.getValueAt(selectedRow, 2)));
        }
    }

    private void updateCustomer() {
        CustomerDto custDto=new CustomerDto();
        
        try {
            System.out.println("cust dto");
            custDto.setCustomerId(Integer.parseInt(txtCustId.getText()));
            custDto.setAddress(txtAddress.getText());
            custDto.setContactNo(Integer.parseInt(txtContactNo.getText()));
            custDto.setFirstName(txtFirstName.getText());
            custDto.setLastName(txtLastName.getText());
            custDto.setEmail(txtEmail.getText());
            
            String result=customerController.updateCustomer(custDto);
            if(result.equals("succeed")){
                JOptionPane.showMessageDialog(rootPane, "Customer Updated Successfully");
                clear();
                loadCustomers();
            }
            else{
                JOptionPane.showMessageDialog(rootPane, "Customer Update Failed");
            }
        } catch (Exception e) {
                JOptionPane.showMessageDialog(rootPane, "Error-Customer Update");
        } 
    }

    private void deleteCustomer() {
        int id=Integer.parseInt(txtCustId.getText());
        int choice=JOptionPane.showConfirmDialog(rootPane, "Are you sure?", "Delete Customer",
                JOptionPane.YES_NO_CANCEL_OPTION,JOptionPane.INFORMATION_MESSAGE);
        try {
            if(choice==JOptionPane.YES_OPTION){
                String result=customerController.deleteCustomer(id);
                if(result.equals("succeed")){
                   JOptionPane.showMessageDialog(null, " Deleted Customer Successfully");
                   clear();
                   loadCustomers();
                }
                else{
                    JOptionPane.showMessageDialog(null, "Delete Customer Failed");
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Error-Customer Delete");    
        }
    }
}
