/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package edu.hotel.layered.view;

import java.awt.Toolkit;
import java.awt.Window;
import java.awt.event.WindowEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author Yasas Randeeka
 */
public class HomeView extends javax.swing.JFrame {

    /**
     * Creates new form HomeView
     */
    public HomeView() {
        initComponents();
    }
    public void close(Window window){
        WindowEvent closeWindow=new WindowEvent(window, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(closeWindow);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jHome = new javax.swing.JPanel();
        lblHomePage = new javax.swing.JLabel();
        btnToHome = new javax.swing.JButton();
        btnManageCust = new javax.swing.JButton();
        btnRoomCategories = new javax.swing.JButton();
        btnRooms = new javax.swing.JButton();
        btnReservations = new javax.swing.JButton();
        btnCancelReservations = new javax.swing.JButton();
        btnToHome1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblHomePage.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        lblHomePage.setText("Home Page");

        btnToHome.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnToHome.setText("Logout");
        btnToHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnToHomeActionPerformed(evt);
            }
        });

        btnManageCust.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnManageCust.setText("Manage Customer");
        btnManageCust.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageCustActionPerformed(evt);
            }
        });

        btnRoomCategories.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnRoomCategories.setText("Manage Room Categories");
        btnRoomCategories.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRoomCategoriesActionPerformed(evt);
            }
        });

        btnRooms.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnRooms.setText("Manage Rooms");
        btnRooms.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRoomsActionPerformed(evt);
            }
        });

        btnReservations.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnReservations.setText("Manage Reservations");
        btnReservations.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReservationsActionPerformed(evt);
            }
        });

        btnCancelReservations.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnCancelReservations.setText("Cancel Reservations");
        btnCancelReservations.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelReservationsActionPerformed(evt);
            }
        });

        btnToHome1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnToHome1.setText("Exit");
        btnToHome1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnToHome1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jHomeLayout = new javax.swing.GroupLayout(jHome);
        jHome.setLayout(jHomeLayout);
        jHomeLayout.setHorizontalGroup(
            jHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jHomeLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(btnToHome1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 97, Short.MAX_VALUE)
                .addComponent(lblHomePage, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(131, 131, 131)
                .addComponent(btnToHome, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
            .addGroup(jHomeLayout.createSequentialGroup()
                .addGap(167, 167, 167)
                .addGroup(jHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnCancelReservations, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnReservations, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRooms, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRoomCategories, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnManageCust, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)))
                .addContainerGap(211, Short.MAX_VALUE))
        );
        jHomeLayout.setVerticalGroup(
            jHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jHomeLayout.createSequentialGroup()
                .addGroup(jHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jHomeLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(lblHomePage))
                    .addGroup(jHomeLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnToHome1)
                            .addComponent(btnToHome))))
                .addGap(28, 28, 28)
                .addComponent(btnManageCust)
                .addGap(18, 18, 18)
                .addComponent(btnRoomCategories)
                .addGap(27, 27, 27)
                .addComponent(btnRooms)
                .addGap(18, 18, 18)
                .addComponent(btnReservations)
                .addGap(29, 29, 29)
                .addComponent(btnCancelReservations)
                .addContainerGap(145, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jHome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(61, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRoomCategoriesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRoomCategoriesActionPerformed
        // TODO add your handling code here:
        close(this);
        new RoomCategoriesView().setVisible(true);
    }//GEN-LAST:event_btnRoomCategoriesActionPerformed

    private void btnManageCustActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageCustActionPerformed
        // TODO add your handling code here:
        close(this);
        new CustomerView().setVisible(true);
    }//GEN-LAST:event_btnManageCustActionPerformed

    private void btnRoomsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRoomsActionPerformed
        close(this);
        new RoomsView().setVisible(true);
    }//GEN-LAST:event_btnRoomsActionPerformed

    private void btnReservationsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReservationsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnReservationsActionPerformed

    private void btnCancelReservationsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelReservationsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelReservationsActionPerformed

    private void btnToHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnToHomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnToHomeActionPerformed

    private void btnToHome1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnToHome1ActionPerformed
        // TODO add your handling code here:
        int choice=JOptionPane.showConfirmDialog(rootPane, "Are you sure?", "Exit From Application",
                JOptionPane.YES_NO_CANCEL_OPTION,JOptionPane.INFORMATION_MESSAGE);

        if(choice==JOptionPane.YES_OPTION){
                System.exit(0);
        }
    }//GEN-LAST:event_btnToHome1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomeView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelReservations;
    private javax.swing.JButton btnManageCust;
    private javax.swing.JButton btnReservations;
    private javax.swing.JButton btnRoomCategories;
    private javax.swing.JButton btnRooms;
    private javax.swing.JButton btnToHome;
    private javax.swing.JButton btnToHome1;
    private javax.swing.JPanel jHome;
    private javax.swing.JLabel lblHomePage;
    // End of variables declaration//GEN-END:variables
}
