/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package edu.hotel.layered.view;

/**
 *
 * @author Yasas Randeeka
 */
public class RoomCategoriesView extends javax.swing.JFrame {

    /**
     * Creates new form RoomCategoriesView
     */
    public RoomCategoriesView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        lblManageRoomCategories = new javax.swing.JLabel();
        lblCategory = new javax.swing.JLabel();
        lblOccupancy = new javax.swing.JLabel();
        cmbobxOccupancy = new javax.swing.JComboBox<>();
        txtCategoryId = new javax.swing.JTextField();
        lblBedsize = new javax.swing.JLabel();
        cmbobxBedsize = new javax.swing.JComboBox<>();
        lblRoomNo = new javax.swing.JLabel();
        cmbobxRoomNo = new javax.swing.JComboBox<>();
        btnAddRoomCategory = new javax.swing.JButton();
        btnSearchRoomCategory = new javax.swing.JButton();
        btnUpdateRoomCategory = new javax.swing.JButton();
        btnToHome = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblManageRoomCategories.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        lblManageRoomCategories.setText("Mange Room Categories");

        lblCategory.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblCategory.setText("Category ID");

        lblOccupancy.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblOccupancy.setText("Occupancy");

        cmbobxOccupancy.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cmbobxOccupancy.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Single", "Double\t", "Triple", "Quad" }));

        txtCategoryId.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        lblBedsize.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblBedsize.setText("Bed Size");

        cmbobxBedsize.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cmbobxBedsize.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Queen", "King", "Twin", "Hollywood Twin", "Double double", "Studio" }));

        lblRoomNo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblRoomNo.setText("Room No");

        cmbobxRoomNo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        btnAddRoomCategory.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnAddRoomCategory.setText("Add");
        btnAddRoomCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddRoomCategoryActionPerformed(evt);
            }
        });

        btnSearchRoomCategory.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnSearchRoomCategory.setText("Search");
        btnSearchRoomCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchRoomCategoryActionPerformed(evt);
            }
        });

        btnUpdateRoomCategory.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnUpdateRoomCategory.setText("Update");
        btnUpdateRoomCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateRoomCategoryActionPerformed(evt);
            }
        });

        btnToHome.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnToHome.setText("Home");
        btnToHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnToHomeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblBedsize, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblOccupancy, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblRoomNo, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(47, 47, 47)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cmbobxOccupancy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cmbobxBedsize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cmbobxRoomNo, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(508, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(89, 89, 89)
                                .addComponent(lblManageRoomCategories))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCategoryId, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(77, 77, 77)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnUpdateRoomCategory, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnSearchRoomCategory, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnAddRoomCategory, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(50, 50, 50)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnToHome)
                        .addGap(35, 35, 35))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblManageRoomCategories)
                    .addComponent(btnToHome))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCategory)
                            .addComponent(txtCategoryId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAddRoomCategory))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblOccupancy)
                            .addComponent(cmbobxOccupancy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblBedsize)
                            .addComponent(cmbobxBedsize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblRoomNo)
                            .addComponent(cmbobxRoomNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(btnSearchRoomCategory)
                        .addGap(18, 18, 18)
                        .addComponent(btnUpdateRoomCategory)))
                .addContainerGap(258, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddRoomCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddRoomCategoryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddRoomCategoryActionPerformed

    private void btnSearchRoomCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchRoomCategoryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSearchRoomCategoryActionPerformed

    private void btnUpdateRoomCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateRoomCategoryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUpdateRoomCategoryActionPerformed

    private void btnToHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnToHomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnToHomeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RoomCategoriesView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RoomCategoriesView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RoomCategoriesView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RoomCategoriesView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RoomCategoriesView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddRoomCategory;
    private javax.swing.JButton btnSearchRoomCategory;
    private javax.swing.JButton btnToHome;
    private javax.swing.JButton btnUpdateRoomCategory;
    private javax.swing.JComboBox<String> cmbobxBedsize;
    private javax.swing.JComboBox<String> cmbobxOccupancy;
    private javax.swing.JComboBox<String> cmbobxRoomNo;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel lblBedsize;
    private javax.swing.JLabel lblCategory;
    private javax.swing.JLabel lblManageRoomCategories;
    private javax.swing.JLabel lblOccupancy;
    private javax.swing.JLabel lblRoomNo;
    private javax.swing.JTextField txtCategoryId;
    // End of variables declaration//GEN-END:variables
}
